### ISSUE TITLE
Add integration tests for Portal using Kurtosis

### ISSUE THREAD

**Issue by gbouv** [kurtosis-tech/kurtosis-portal#30]
The portal should be tested using Kurtosis.
We should build 2 docker images, both using as a base https://hub.docker.com/_/docker to have docker running
- The server should expose 3 ports: one for the portal server, one for kurtosis backend (i.e. docker) and one for port tunnelling
- The client should add the context corresponding to the server container using its IP and 3 ports, connects to it, and run a simple starlark script

The docker in docker image seem to by default expose the docker port, and there's also instructions here on how to plug certs to it, if we need. Seems that we have everything we need here

**Comment by h4ck3rk3y** [comment]
Standup -Big Issue - how do we query GRPC within Kurtosis?

Looking for something nice but might be falling back to Go/TS test while would love to write wait/asserts in Stalrakr. Will write a project Notion doc that we could prioritize.

We can't dog food portal without it.

Urgency - Could write in Go. The portal makes it easier to test KT in KT and @mieubrisse (KT)  wanted us to dog food this. Could explore adding this as an entry to Q2P1 and chat with Product.
